Fixing unmounting of layers during runtime
rnmapbox/maps pull request #1843
Opened 2022-04-16 17:46 UTC by rastapasta

## Description

In the new swift implementation, the MapView's removeReactSubview is never called by the RTCManager, resulting in removed React Components not being unmounted from the map.

To solve this, the corresponding super methods are called resulting in the removeReactSubview method being called and layers removed from the map.

## Checklist

- [X] I have tested this on a device/simulator for each compatible OS
- [ ] I formatted JS and TS files with running `yarn lint:fix` in the root folder
- [ ] I updated the documentation with running `yarn generate` in the root folder
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typings files (`index.d.ts`)
- [ ] I added/ updated a sample (`/example`)

2022-04-16 20:42 UTC, mfazekas requested changes
@rastapasta can you add a short sample code, where the issue occurs.
I assume something like this, and when setting visible to false the component still rendered on the map?!
```
<MapView>
   {visible && <ShapeSource>
       <CircleLayer .../>
     </ShapeSource>
   }
</MapView>
```

2022-04-16 20:42 UTC, mfazekas commented on ios/RCTMGL-v10/RCTMGLMapView.swift
> +    super.insertReactSubview(subview, at: atIndex)
Interesting that we haven't called `insertReactSubview` in prev implementation but we did overwrote reactSubviews. 

Not sure if it worth the trouble to not do the pre v10 implementation, calling `super.insertReactSubview` sounds simpler. 

See https://github.com/rnmapbox/maps/blob/f42cacc60ad04182d31b6228e6bc71cfcd059ea8/ios/RCTMGL/RCTMGLMapView.m#L217-L220

2022-04-16 21:52 UTC, rastapasta commented on ios/RCTMGL-v10/RCTMGLMapView.swift
> +    super.insertReactSubview(subview, at: atIndex)
Found that interesting as well when digging through the code to explain its behavior, though found no advantage of re-implementing the reactSubviews as done previously.

2022-04-16 22:35 UTC, rastapasta commented on ios/RCTMGL-v10/RCTMGLMapView.swift
> +    super.insertReactSubview(subview, at: atIndex)
@mfazekas your guess was spot on! added an example to the PR description.

2022-04-17 05:32 UTC, mfazekas commented on ios/RCTMGL-v10/RCTMGLMapView.swift
> +    super.insertReactSubview(subview, at: atIndex)
The only difference I can think of is that views were not added, to MapView before. 

So this 
```
<MapVIew>
  <View style={{backgroundColor: 'red', width: 100, height: 100}} />
</MapView>
```

will now add a view into MapView, not sure if that's works on android.

Let's go with this implementation for now, we can revisit later.

2022-04-17 05:32 UTC, merged