Add handler and documentation for MapView's scaleBarEnabled prop (v10, iOS)
rnmapbox/maps pull request #1846
Opened 2022-04-17 13:28 UTC by rastapasta

## Description

v10 comes with a scale bar in the top left - this PR adds a ```scaleBarEnabled``` prop handler to the MapView, allowing to enable or disable the scale bar.

## Checklist

- [X] I have tested this on a device/simulator for each compatible OS
- [X] I added the prop to the `MapView.md`
- [ ] I mentioned this change in `CHANGELOG.md`

## Code example

```javascript
<MapView scaleBarEnabled={false} />
```

2022-04-17 14:41 UTC, mfazekas requested changes
You'll need to

2022-04-17 14:41 UTC, mfazekas commented on index.d.ts
> +  scaleBarEnabled?: boolean;
This also needs to be added to MapView.js and run `yarn generate`

2022-04-18 11:58 UTC, rastapasta commented on index.d.ts
> +  scaleBarEnabled?: boolean;
@mfazekas thanks for letting me know, noted for future changes of props

2022-04-20 16:48 UTC, mfazekas commented
@rastapasta thanks looks good to me, can you rebase so it can be merged?!

2022-04-20 17:03 UTC, rastapasta commented
Aloha @mfazekas thanks for the review, merged main in and should be ready to go!

2022-04-22 14:23 UTC, felixgourdeau commented on ios/RCTMGL-v10/RCTMGLMapView.swift
> +  @objc func setReactScaleBarEnabled(_ value: Bool) {
There is a [third option](https://docs.mapbox.com/ios/maps/api/10.4.3/Enums/OrnamentVisibility.html) available: `adaptive`.
Should we expose a type instead of a Bool for this option?

2022-04-22 14:25 UTC, felixgourdeau commented on ios/RCTMGL-v10/RCTMGLMapView.swift
> +  @objc func setReactScaleBarEnabled(_ value: Bool) {
There is also [two other props](https://docs.mapbox.com/ios/maps/api/10.4.3/Structs/ScaleBarViewOptions.html#/s:10MapboxMaps19ScaleBarViewOptionsV10visibilityAA18OrnamentVisibilityOvp) we can expose for the ScaleBar: `margin` and `position`

2022-04-22 19:28 UTC, merged

2022-04-23 00:02 UTC, rastapasta commented on ios/RCTMGL-v10/RCTMGLMapView.swift
> +  @objc func setReactScaleBarEnabled(_ value: Bool) {
Ahoi @felixgourdeau , great that you spotted that possibility - would recommend another PR implementing that props. Cheers!