feat: adding back bounds
rnmapbox/maps pull request #2015
Opened 2022-06-30 13:19 UTC by Andarius

## Description

- Adding  `bounds` to `<MapboxGL.Camera />`.
- Fix for padding with `bounds`.
- Adding None to `animationMode`.
- Fix zoom/scroll/rotate/logo enabled/disabled

## Checklist

- [ ] I have tested this on a device/simulator for each compatible OS
- [ ] I updated the documentation with running `yarn generate` in the root folder
- [ ] I mentioned this change in `CHANGELOG.md`
- [X] I updated the typings files (`index.d.ts`)
- [ ] I added/ updated a sample (`/example`)

2022-06-30 17:22 UTC, felixgourdeau approved these changes

2022-06-30 17:27 UTC, Andarius commented
I'm doing some testing, and it appears that when rendering more than 2 maps, the zoom cannot be computed
`E/Mapbox: [maps-core]: {obitrain.obiapp}[General]: Unable to calculate appropriate zoom level for bounds. Vertical or horizontal padding is greater than map's height or width.` 
Not sure why, maybe related to https://github.com/rnmapbox/maps/pull/1057 ?

2022-07-01 13:53 UTC, felixgourdeau commented on android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.kt
> +        mapView.gestures.rotateEnabled
`mapView.gestures.rotateEnabled = rotateEnabled`

2022-07-01 14:25 UTC, mfazekas commented on android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/camera/CameraStop.java
> -            int paddingTop = getBoundsPaddingByKey(readableMap, "boundsPaddingTop");
Are you sure about the `boundsPaddingTop` => `paddingTop` rename?! I think on JS part we still use `boundsPaddingTop` as I looked.

2022-07-01 14:40 UTC, mfazekas commented on android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/camera/CameraStop.java
> -            int paddingTop = getBoundsPaddingByKey(readableMap, "boundsPaddingTop");
Ok it seems that here we still use the old names.
https://github.com/rnmapbox/maps/blob/1ae89df048841327c871553f76a8d21181ed13c3/javascript/components/MapView.js#L632-L635
But other native code uses `paddingTop` not `boundsPaddingTop` so this change seems to be ok.

This was likely changed in `https://github.com/rnmapbox/maps/pull/1538`. I mean boundsPaddingTop to just paddingTop.

2022-07-01 14:52 UTC, Andarius commented on android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/camera/CameraStop.java
> -            int paddingTop = getBoundsPaddingByKey(readableMap, "boundsPaddingTop");
Should I mark this as resolved or do you want me to make some changes?

2022-07-05 08:05 UTC, mfazekas commented on javascript/components/Camera.js
>          return MapboxGL.CameraModes.Move;
`None` is same as `Move`, but it's a bit of a mess as most implementation exports `MapboxGL.CameraModes.None`, but iOS on v10 only export `Move`

2022-07-05 09:30 UTC, Andarius commented on javascript/components/Camera.js
>          return MapboxGL.CameraModes.Move;
How do you disable the animation on iOS?

2022-07-06 20:34 UTC, mfazekas commented on javascript/components/Camera.js
>          return MapboxGL.CameraModes.Move;
`Move` just jumps without animation. 

https://github.com/rnmapbox/maps/pull/1838#issuecomment-1100638219

2022-07-24 14:42 UTC, felixgourdeau commented
@mfazekas @Andarius should we merge this PR for now, and fix the issue with more than 2 maps?

2022-07-24 15:04 UTC, mfazekas commented
> @mfazekas @Andarius should we merge this PR for now, and fix later the issue with more than 2 maps?

Yes sorry, let's merge this. Please update code so it can be merged.

2022-07-25 00:15 UTC, felixgourdeau approved these changes

2022-07-26 07:07 UTC, mfazekas requested changes
I think logoEnabled, and compassEnabled changes needs revert

2022-07-26 07:07 UTC, mfazekas commented on android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.kt
> -        mapView!!.setReactCompassEnabled(compassEnabled!!);
Is this intentional?! 


setReactCompassEnabled sound like a better implementation

https://github.com/rnmapbox/maps/blob/main/android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.kt#L855

2022-07-26 07:07 UTC, mfazekas commented on android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.kt
> -        mapView!!.setReactLogoEnabled(logoEnabled);
What's wrong with `setReactLogoEnabled` ?!

2022-07-26 07:26 UTC, Andarius commented on android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.kt
> -        mapView!!.setReactCompassEnabled(compassEnabled!!);
You are right, my bad. I'm reverting

2022-07-26 07:30 UTC, Andarius commented on android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.kt
> -        mapView!!.setReactCompassEnabled(compassEnabled!!);
Just for information, what's the point of `compassEnabled!!` and not just `compassEnabled` ?

2022-07-26 07:36 UTC, mfazekas commented on android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.kt
> -        mapView!!.setReactCompassEnabled(compassEnabled!!);
I guess it's a mistake, feel free to remove `!!`

2022-07-26 08:46 UTC, mfazekas approved these changes

2022-07-26 09:36 UTC, merged