Feature: compassFadeWhenNorth
rnmapbox/maps pull request #2068
Opened 2022-07-23 14:31 UTC by mysport12

## Description

Added the ability to control whether or not the compass fades out when pointing north. On Android the default was true, and on iOS the default was false. This brings consistency across platforms by defaulting to true ("breaking" for iOS) and adds the ability to toggle this behavior on/off with a new prop

## Checklist

- [x] I have tested this on a device/simulator for each compatible OS
- [x] I updated the documentation with running `yarn generate` in the root folder
- [ ] I mentioned this change in `CHANGELOG.md`
- [x] I updated the typings files (`index.d.ts`)
- [ ] I added/ updated a sample (`/example`)

2022-07-23 17:15 UTC, mfazekas approved these changes

2022-07-23 17:25 UTC, mfazekas requested changes
Thanks much looks awesome. 

I think android logic might need an update.

I'm also thinking about setting the default it to `false`. 
It could be weird if someone set just `compassEnable={true}` and then doesn't sees the compass because it's hidden as it's north.

Whay do you think?!

2022-07-23 17:25 UTC, mfazekas commented on ios/RCTMGL-v10/RCTMGLMapView.swift
> +    mapView.ornaments.options.compass.visibility = value ? .adaptive : .visible
I'm not sure if this logic works with `compassEnabled={false} compassFadeWhenNorth={false}`, I think it just will show the compass

2022-07-23 20:03 UTC, mysport12 commented on ios/RCTMGL-v10/RCTMGLMapView.swift
> +    mapView.ornaments.options.compass.visibility = value ? .adaptive : .visible
Good catch and valid point! I will default to false, and add some checks to make sure it works in all scenarios

2022-07-23 20:12 UTC, mysport12 commented on ios/RCTMGL-v10/RCTMGLMapView.swift
> +    mapView.ornaments.options.compass.visibility = value ? .adaptive : .visible
I pushed an update. Tested on iOS for the logic issue you caught above. I also noticed that Android/iOS had different defaults for compassEnabled. I set both platforms to false for consistency but feel free to change them to true by default.

2022-07-25 20:22 UTC, mfazekas commented
@mysport12 generated should commited according to CI: https://github.com/rnmapbox/maps/runs/7488241923?check_suite_focus=true

2022-07-25 20:33 UTC, mysport12 commented
Should be all set now

2022-07-26 05:17 UTC, mfazekas approved these changes

2022-07-26 08:53 UTC, merged