iOS V10 PointAnnotation Drag and Selection Support
rnmapbox/maps pull request #2077
Opened 2022-07-29 17:20 UTC by mysport12

## Description

- Added draggable support for PointAnnotation
- Added support for onDrag, onDragEnd, onDragStart, onDeselected, and onSelected

## Checklist

- [x] I have tested this on a device/simulator for each compatible OS
- [ ] I updated the documentation with running `yarn generate` in the root folder
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typings files (`index.d.ts`)
- [ ] I added/ updated a sample (`/example`)

2022-07-29 21:04 UTC, mfazekas reviewed
Thanks, looks awesome!

2022-07-29 21:04 UTC, mfazekas commented on android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/modules/RCTMGLOfflineModule.kt
> +            Log.d("TAG", "${e}... file move unsuccessful")
```suggestion
            Log.e("RCTMGLOfflineModule", "${e}... file move unsuccessful")
```

2022-07-29 21:04 UTC, mfazekas commented on android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/modules/RCTMGLOfflineModule.kt
> +            Log.d("TAG","v10 cache directory created successfully")
```suggestion
```

I think this can be removed

2022-07-31 12:19 UTC, mfazekas requested changes

2022-07-31 12:19 UTC, mfazekas commented on ios/RCTMGL-v10/RCTMGLPointAnnotation.swift
> +class RCTMGLPointAnnotation : RCTMGLSource {
PointAnnotation is not a source, we can extract some common subclass but inheriting from `RCTMGLSource` sounds fishy for me.

2022-08-08 04:40 UTC, mysport12 commented on ios/RCTMGL-v10/RCTMGLPointAnnotation.swift
> +class RCTMGLPointAnnotation : RCTMGLSource {
Sorry I haven't responded to this yet. We needed to jump back to v8 and I haven't had a chance to look into this further. If I can this week I will.

2022-08-15 19:19 UTC, mysport12 commented on ios/RCTMGL-v10/RCTMGLPointAnnotation.swift
> +class RCTMGLPointAnnotation : RCTMGLSource {
@mfazekas attempted to break this out to a common subclass per your request. I am not the most proficient at Swift so there may be a cleaner/better way to go about it. Let me know your thoughts.

2022-08-19 06:01 UTC, mfazekas approved these changes

2022-08-21 06:13 UTC, merged