Reorganize animated classes
rnmapbox/maps pull request #2167
Opened 2022-08-26 22:04 UTC by naftalibeder

This fixes a bug caused by #2161, where `AnimatedPoint` and `AnimatedShape` were not properly exported.

In working on this, I realized that the `Animated*` objects in `utils` weren't really utilities - the classes. and I wanted to differentiate between helper classes and the interfaces that they rely on, so I did a bit of a reorganization.

This also deprecates (but still supports) `AnimatedShape` in favor of the more accurate name `AnimatedLineString`.

There were also some internal imports and tests that needed fixing.

This shouldn't break anything except full-path imports, e.g. `import AnimatedPoint from '@rnmapbox/maps/javascript/utils/animated/AnimatedPoint`, which I don't think should be something that we need backwards compatibility for.

2022-08-27 09:29 UTC, mfazekas commented on javascript/utils/animated/Animated.js
> -  CoordinatesArray: AnimatedCoordinatesArray,
Isn't it a breaking change to remove those?!

2022-08-27 09:30 UTC, mfazekas commented on javascript/index.js
> -  AnimatedMapPoint,
AnimatedMapPoint => AnimatedPoint is a breaking change

2022-08-27 09:32 UTC, mfazekas commented on plugin/build/withMapbox.js
> +    }
Not sure about that

2022-08-27 13:03 UTC, naftalibeder commented on plugin/build/withMapbox.js
> +    }
Oops that was a mistake, thought I reverted it 😳

2022-08-27 13:11 UTC, naftalibeder commented on javascript/utils/animated/Animated.js
> -  CoordinatesArray: AnimatedCoordinatesArray,
Ah true. The animated stuff in particular has so many different import paths. If you want to keep support for all the different imports, would you be all right if I add them back in with a deprecated tag?

I know as a user of `AnimatedPoint` etc., I’ve often found it confusing to not just have a simple import like most elements in this library, e.g. `import { AnimatedPoint } from ‘@rnmapbox/maps’`

2022-08-27 17:04 UTC, mfazekas commented on javascript/utils/animated/Animated.js
> -  CoordinatesArray: AnimatedCoordinatesArray,
Yes if we can deprecate them that's fine. We can also add a `deprecatedClass` to `utils/deprecation.js` so we could do something like:

```js
   CoordinatesArray: deprecatedClass(AnimatedCoordinatesArray, "Animated.CoordinatesArray is deprecated, please use AnimatedCoordinatesArray"),
```

```js
function deprecatedClass(klass,message) {
  return class extends klass {
    constructor(...args) {
      console.log(`Deprecated: ${message}`)
      super(...args)
    }
  }
}
```

2022-08-29 19:36 UTC, naftalibeder commented on plugin/build/withMapbox.js
> +    }
Oh yeah weird - this is generated code.

2022-08-29 19:49 UTC, naftalibeder commented
@mfazekas I think this should be good to go.

2022-09-02 09:00 UTC, mfazekas requested changes
Sorry I forget to post my comment, pls rename back to AnimatedShape, otherwise looks great!

2022-09-06 18:27 UTC, naftalibeder commented on javascript/classes/AnimatedLineString.js
> -      'AnimatedShape could not obtain AnimatedWithChildren base class',
Sorry for the wait - this should be good to go, lmk!

2022-09-06 18:31 UTC, mfazekas approved these changes

2022-09-06 18:32 UTC, mfazekas approved these changes
LGTM

There are some lint issues to be fixed

2022-09-06 22:04 UTC, naftalibeder commented
All right, everything works locally for me. For some reason the test action just failed with the error relating to `uncommitted changes`, which is weird for the CI. Running again...

I updated a few dependencies related to testing, can you verify you're okay with everything?

2022-09-07 06:07 UTC, mfazekas approved these changes
Looks good to me, the CI still needs to be fixed.

2022-09-07 06:07 UTC, mfazekas commented on __tests__/components/UserLocation.test.js
> +    }, 1000);
👍  awesome! thanks for correcting the async tests

```suggestion
    });
```

Do we need test specific timeout?! We could also lower the default timeout can't we?!

2022-09-07 14:21 UTC, naftalibeder commented on .eslintrc.js
> +    'plugin:jest/recommended',
Whoops! 😆

2022-09-07 14:28 UTC, naftalibeder commented on __tests__/components/UserLocation.test.js
> +    }, 1000);
That's right, that was left over from a different fix attempt. Good eye!

2022-09-07 15:29 UTC, naftalibeder commented
OK, merging, thanks!

2022-09-07 15:29 UTC, merged

2022-09-07 15:31 UTC, mfazekas commented
@naftalibeder pls fix CI too