Location Manager Object Initialisation removed
rnmapbox/maps pull request #2586
Opened 2023-02-04 12:41 UTC by mahipalsingh-syt

## Description

Fixes #<issue-number>

Added `your feature` that allows ...

## Checklist

- [ ] I have tested this on a device/simulator for each compatible OS
- [ ] I updated the documentation with running `yarn generate` in the root folder
- [ ] I updated the typings files - if js interface was changed (`index.d.ts`)
- [ ] I added/ updated a sample - if a new feature was implemented (`/example`)

## Screenshot OR Video

2023-02-04 12:42 UTC, mahipalsingh-syt commented
This issue i have fixed in this PR
https://github.com/rnmapbox/maps/issues/2583

2023-02-04 17:53 UTC, mfazekas requested changes

2023-02-04 17:53 UTC, mfazekas commented on javascript/modules/location/locationManager.js
> +export default LocationManager;
I agree that initializing LocationManager is problematic, but this is a breaking change. As now we export a class and they have to create an instance rather than calling methods on it.

2023-02-06 07:15 UTC, mahipalsingh-syt commented
@mfazekas   i have revert the changes related to initializing of LocationManager. 
and we can handle the LocationManager with `requestsAlwaysUse` start method should call only when it is `true`

So i have updated case of `_handleAppStateChange` method it will call the listener only when `requestsAlwaysUse` will true

2023-02-06 07:40 UTC, mfazekas commented on javascript/modules/location/locationManager.js
> +    if (this._requestsAlwaysUse) {
What about calling `start` only if we have listeners?! 

```js
if (this._listeners.length > 0) {
  this.start();
}
```

2023-02-06 10:20 UTC, mahipalsingh-syt commented on javascript/modules/location/locationManager.js
> +    if (this._requestsAlwaysUse) {
yes , i think listener check good to check for "Start". I'll update and check

2023-02-07 20:04 UTC, merged