Refactor camera bounds and zoom handling on Android
rnmapbox/maps pull request #3375
Opened 2024-02-13 18:25 UTC by naftalibeder

This is a refactor to match #3354 on Android.

It didn't have the same double-padding issue, but Android also lacked the ability to zero out min and max zoom levels, and the equality check for the `ts` (?) property was preventing any camera updates.

(I'm not sure if that's due to a recent change, but it didn't seem like the property was necessary. Correct me if I'm wrong!)

This PR also includes some code cleanup, improved Kotlin syntax, etc.

2024-02-13 18:54 UTC, mfazekas requested changes

2024-02-13 18:54 UTC, mfazekas commented on android/src/main/java/com/rnmapbox/rnmbx/components/camera/RNMBXCamera.kt
> -    var ts: Int? = null;
please see https://github.com/rnmapbox/maps/pull/3372 and https://github.com/rnmapbox/maps/pull/3349 on the `ts`  . It's needed to fabric to prevent reapplying the camera on each re-render.

2024-02-13 21:30 UTC, naftalibeder commented on android/src/main/java/com/rnmapbox/rnmbx/components/camera/RNMBXCamera.kt
> -    var ts: Int? = null;
Ok makes sense. When passing props instead of calling `setCamera`, the native value for `stop.ts` is `null`. Does [this](https://github.com/rnmapbox/maps/pull/3375/commits/5abbc52853012e13c883fb37ed55f8ed57092605) seem reasonable?

2024-02-14 10:55 UTC, mfazekas commented on android/src/main/java/com/rnmapbox/rnmbx/components/camera/RNMBXCamera.kt
> -    var ts: Int? = null;
That probably works, but I've ended up removing `setNativeProps` which seems to be somewhat implemented on fabric, but it's kind of broken, on fabric and the stop applied by setNativeProp seems to be reapply on every pre-render.

#3376 adds a CamereModule with updateCameraStop instead

2024-02-15 06:41 UTC, mfazekas commented on android/src/main/old-arch/com/facebook/react/viewmanagers/RNMBXCameraManagerDelegate.java
This is a generated file.

2024-02-15 06:41 UTC, mfazekas commented
@naftalibeder can we split the changes to different PR-s it's very hard to review this way, that refactoring and bugfix and cleanup is all there. 

Also if you're fixing an issue can you add simple component to demonstrate the issue.

2024-02-15 10:46 UTC, vasilring commented
@mfazekas @naftalibeder Since the latest update im getting and error that rnmapboxcameramodule doesnt exist on registry.
<img width="376" alt="Screenshot 2024-02-15 at 12 42 34" src="https://github.com/rnmapbox/maps/assets/111189545/f44c93cc-aeae-4008-97fa-e450685d081e">

The version of mapbox before that has a problem for android devices. When the map opens on android the animationMode: flyTo doesnt work, but for IOS works.

Is that the issue you were talking about?

2024-02-15 12:07 UTC, mfazekas commented
> @mfazekas @naftalibeder Since the latest update im getting and error that rnmapboxcameramodule doesnt exist on registry. <img alt="Screenshot 2024-02-15 at 12 42 34" width="376" src="https://private-user-images.githubusercontent.com/111189545/305043550-f44c93cc-aeae-4008-97fa-e450685d081e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5OTg5OTQsIm5iZiI6MTcwNzk5ODY5NCwicGF0aCI6Ii8xMTExODk1NDUvMzA1MDQzNTUwLWY0NGM5M2NjLWFlYWUtNDAwOC05N2ZhLWU0NTA2ODVkMDgxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQxMjA0NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjA5ZDg2Nzg0ZmU5ZDM5MmRmM2RhYzUwMzU2ZGE1ZGFiNzNiMmE0NDYyZDY5NGMxNDExOGIwODQ2ZjU1MzI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wF07CmF76InHaveGzafcgZ1cQs7k6Fhdh9e-_uIL8_I">
> 
> The version of mapbox before that has a problem for android devices. When the map opens on android the animationMode: flyTo doesnt work, but for IOS works.
> 
> Is that the issue you were talking about?

For the camera module doesn't exists, have you executed pod install after updating the @rnmapbox/maps in node_modules?
Then you'll need to rebuild the app in Xcode, or use npx react-native run-ios or similar

2024-02-15 14:41 UTC, vasilring commented
> > @mfazekas @naftalibeder Since the latest update im getting and error that rnmapboxcameramodule doesnt exist on registry. <img alt="Screenshot 2024-02-15 at 12 42 34" width="376" src="https://private-user-images.githubusercontent.com/111189545/305043550-f44c93cc-aeae-4008-97fa-e450685d081e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5OTg5OTQsIm5iZiI6MTcwNzk5ODY5NCwicGF0aCI6Ii8xMTExODk1NDUvMzA1MDQzNTUwLWY0NGM5M2NjLWFlYWUtNDAwOC05N2ZhLWU0NTA2ODVkMDgxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQxMjA0NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjA5ZDg2Nzg0ZmU5ZDM5MmRmM2RhYzUwMzU2ZGE1ZGFiNzNiMmE0NDYyZDY5NGMxNDExOGIwODQ2ZjU1MzI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wF07CmF76InHaveGzafcgZ1cQs7k6Fhdh9e-_uIL8_I">
> > The version of mapbox before that has a problem for android devices. When the map opens on android the animationMode: flyTo doesnt work, but for IOS works.
> > Is that the issue you were talking about?
> 
> For the camera module doesn't exists, have you executed pod install after updating the @rnmapbox/maps in node_modules? Then you'll need to rebuild the app in Xcode, or use npx react-native run-ios or similar

Actually no, I'm using the rnmapbox with Expo managed workflow, and before the update to 10.1.13 it was working allright with EAS build. Do I need to do pod install even with managed workflow?

2024-02-15 15:07 UTC, naftalibeder commented
> @naftalibeder can we split the changes to different PR-s

My bad - I got a little carried away. Will do!

2024-02-15 16:11 UTC, mfazekas commented
> > > @mfazekas @naftalibeder Since the latest update im getting and error that rnmapboxcameramodule doesnt exist on registry. <img alt="Screenshot 2024-02-15 at 12 42 34" width="376" src="https://private-user-images.githubusercontent.com/111189545/305043550-f44c93cc-aeae-4008-97fa-e450685d081e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5OTg5OTQsIm5iZiI6MTcwNzk5ODY5NCwicGF0aCI6Ii8xMTExODk1NDUvMzA1MDQzNTUwLWY0NGM5M2NjLWFlYWUtNDAwOC05N2ZhLWU0NTA2ODVkMDgxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQxMjA0NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjA5ZDg2Nzg0ZmU5ZDM5MmRmM2RhYzUwMzU2ZGE1ZGFiNzNiMmE0NDYyZDY5NGMxNDExOGIwODQ2ZjU1MzI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wF07CmF76InHaveGzafcgZ1cQs7k6Fhdh9e-_uIL8_I">
> > > The version of mapbox before that has a problem for android devices. When the map opens on android the animationMode: flyTo doesnt work, but for IOS works.
> > > Is that the issue you were talking about?
> > 
> > 
> > For the camera module doesn't exists, have you executed pod install after updating the @rnmapbox/maps in node_modules? Then you'll need to rebuild the app in Xcode, or use npx react-native run-ios or similar
> 
> Actually no, I'm using the rnmapbox with Expo managed workflow, and before the update to 10.1.13 it was working allright with EAS build. Do I need to do pod install even with managed workflow?

I could not repro the issue in a new expo project, yes you'll need to run eas build again after @rnmapbox/maps update. Pls open a discussion, if it doesn't fix as it's not related to this PR

2024-02-15 17:09 UTC, naftalibeder commented
@mfazekas Updated the description at the top and simplified changes - let me know what you think.

2024-02-15 21:11 UTC, mfazekas approved these changes

2024-02-15 21:11 UTC, mfazekas commented on android/src/main/java/com/rnmapbox/rnmbx/components/camera/RNMBXCamera.kt
> +import android.util.Log
Is log used?

2024-02-15 21:15 UTC, naftalibeder commented on android/src/main/java/com/rnmapbox/rnmbx/components/camera/RNMBXCamera.kt
> +import android.util.Log
Oops, no. Fixed.

2024-02-15 21:19 UTC, naftalibeder commented
@mfazekas Weird, it seems like my edit to the description didn't save properly before, but it was still cached locally. I just resubmitted it.

2024-02-15 21:42 UTC, vasilring commented
> > > > @mfazekas @naftalibeder Since the latest update im getting and error that rnmapboxcameramodule doesnt exist on registry. <img alt="Screenshot 2024-02-15 at 12 42 34" width="376" src="https://private-user-images.githubusercontent.com/111189545/305043550-f44c93cc-aeae-4008-97fa-e450685d081e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5OTg5OTQsIm5iZiI6MTcwNzk5ODY5NCwicGF0aCI6Ii8xMTExODk1NDUvMzA1MDQzNTUwLWY0NGM5M2NjLWFlYWUtNDAwOC05N2ZhLWU0NTA2ODVkMDgxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQxMjA0NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjA5ZDg2Nzg0ZmU5ZDM5MmRmM2RhYzUwMzU2ZGE1ZGFiNzNiMmE0NDYyZDY5NGMxNDExOGIwODQ2ZjU1MzI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wF07CmF76InHaveGzafcgZ1cQs7k6Fhdh9e-_uIL8_I">
> > > > The version of mapbox before that has a problem for android devices. When the map opens on android the animationMode: flyTo doesnt work, but for IOS works.
> > > > Is that the issue you were talking about?
> > > 
> > > 
> > > For the camera module doesn't exists, have you executed pod install after updating the @rnmapbox/maps in node_modules? Then you'll need to rebuild the app in Xcode, or use npx react-native run-ios or similar
> > 
> > 
> > Actually no, I'm using the rnmapbox with Expo managed workflow, and before the update to 10.1.13 it was working allright with EAS build. Do I need to do pod install even with managed workflow?
> 
> I could not repro the issue in a new expo project, yes you'll need to run eas build again after @rnmapbox/maps update. Pls open a discussion, if it doesn't fix as it's not related to this PR

I see thank you! Creating a new project and installing all dependencies fixed the issue.

2024-02-18 07:18 UTC, merged