Support for iOS 12.4 with Mapbox Maps SDK v11
rnmapbox/maps pull request #3433
Opened 2024-03-25 14:21 UTC by hexadecy

## Description

Fixes #3432

- Change the requirement of Mapbox v11 from iOS 13.0 down to 12.4

Change in /example
- Add .java-version 17 for jenv
- Upgrade react-native from 0.73.0 to 0.73.6
- Add packageManager info for node.js corepack

## Checklist
- [x] I've read `CONTRIBUTING.md`
- [x] I updated the doc/other generated code by running `yarn generate` in the root folder
- [x] I have tested the new feature on `/example` app.
  - [x] In V11 mode/ios with React-Native 0.72.11 target ios 12.4
  - [x] In V10 mode/ios with React-Native 0.72.11 target ios 12.4
  - [x] In V11 mode/ios with React-Native 0.73.6 target ios 13.4
  - [x] In V10 mode/ios with React-Native 0.73.6 target ios 13.4
  - [ ] In New Architecture V10 mode/ios
  - [ ] In V11 mode/android
  - [x] In V10 mode/android
  - [ ] In New Architecture V10 mode/android

2024-03-26 05:47 UTC, mfazekas commented
@hexadecy thanks for the PR, can you please separate them?

2024-03-26 05:52 UTC, mfazekas requested changes
pls separate the PR

2024-03-26 05:52 UTC, mfazekas commented on example/ios/Podfile
> +      # https://github.com/facebook/react-native/issues/43335
If this is solved by rn 0.73.6 then let's use that, instead of cocapods magic

2024-03-26 05:55 UTC, mfazekas commented on example/.java-version
> +17.0
pls explain why this is needed. Does it present in a new project created by `npx react-native init`

2024-03-26 11:09 UTC, hexadecy commented on example/ios/Podfile
> +      # https://github.com/facebook/react-native/issues/43335
There are compilation problems on M1 with 0.73.1+, it's the reason why I returned to 0.73.0
https://github.com/facebook/react-native/issues/42112

2024-03-26 11:12 UTC, hexadecy commented on example/.java-version
> +17.0
It's not needed, I was on Java 11 by default.
Do you want me to remove it?

2024-03-29 14:26 UTC, mfazekas commented on example/.java-version
> +17.0
Pls open separate PR-s for QOL's, and the one addressing the specific issue of building for 12.4. Also try to add explanation for the changes in PR description. 

I'm not very fond of QOL changes as a QOL change in one setup will be a PITA in other setups.

2024-03-29 15:18 UTC, hexadecy commented on example/.java-version
> +17.0
Ok, I understand there are so many _standards_ 😮‍💨

I've reset my branch (this PR).

2024-03-29 15:22 UTC, hexadecy commented on example/ios/Podfile
> +      # https://github.com/facebook/react-native/issues/43335
I've tested without Flipper. I'll make a new PR for it later.

2024-04-03 17:59 UTC, hexadecy commented
> pls separate the PR

Done

2024-04-04 13:09 UTC, mfazekas approved these changes

2024-04-07 04:50 UTC, merged