feat: Add bounds to raster source
rnmapbox/maps pull request #3672
Opened 2024-10-29 14:43 UTC by Elter71

## Description

Added `bounds support for RasterSource` . Now, you can limit the bounds within which raster tiles will render.

## Checklist

- [X] I've read `CONTRIBUTING.md`
- [x] I updated the doc/other generated code with running `yarn generate` in the root folder
- [x] I have tested the new feature on `/example` app.
  - [x] In V11 mode/ios
  - [x] In New Architecture mode/ios
  - [x] In V11 mode/android
  - [x] In New Architecture mode/android
- [X] I added/updated a sample - if a new feature was implemented (`/example`)

## Screenshot OR Video
![Screenshot_1730212439](https://github.com/user-attachments/assets/da698d61-7305-43e1-8715-94c40649a499)
![Simulator Screenshot - iPhone SE (3rd generation) - 2024-10-29 at 15 34 47](https://github.com/user-attachments/assets/57338869-b302-4df3-9aec-7865632538f7)

2024-10-29 16:44 UTC, mfazekas requested changes
@Elter71 Thanks much amazing work!

Some minor nitpicks

2024-10-29 16:44 UTC, mfazekas commented on android/src/main/java/com/rnmapbox/rnmbx/components/styles/sources/RNMBXRasterSourceManager.kt
> +            if (readableArray.size() == 4) {
Is this check necessary here? We'll just silently error if the size is not 4

2024-10-29 16:44 UTC, mfazekas commented on android/src/main/java/com/rnmapbox/rnmbx/components/styles/sources/RNMBXTileSource.kt
> +             val boundsArray = bounds!!.clone()
do we need `!!` we've tested above for null already

2024-10-30 09:59 UTC, Elter71 commented on android/src/main/java/com/rnmapbox/rnmbx/components/styles/sources/RNMBXTileSource.kt
> +             val boundsArray = bounds!!.clone()
Without this, you will get an error:

`Smart cast to 'Array<Double>' is impossible, because 'bounds' is a mutable property that could have been changed by this time FAILURE: Build failed with an exception.`

2024-10-30 10:13 UTC, Elter71 commented on android/src/main/java/com/rnmapbox/rnmbx/components/styles/sources/RNMBXRasterSourceManager.kt
> +            if (readableArray.size() == 4) {
Without this, you will get an error like this:
![Screenshot_1730282753](https://github.com/user-attachments/assets/1e8438f3-f1cf-4363-bce9-0cd316fb67eb)

Personally, I prefer a more direct message, but I leave it up to you.

2024-10-30 10:13 UTC, mfazekas commented on android/src/main/java/com/rnmapbox/rnmbx/components/styles/sources/RNMBXTileSource.kt
> +             val boundsArray = bounds!!.clone()
We should be able to do something like this:
```kt
bounds?.let { 
   builder.bounds(Arrays.asList(it))
}
```

2024-10-30 10:26 UTC, mfazekas commented on android/src/main/java/com/rnmapbox/rnmbx/components/styles/sources/RNMBXRasterSourceManager.kt
> +            if (readableArray.size() == 4) {
Sorry, mybad, you're right I've missed the Logger.e at the end. 

Nitpick: Can please you rewrite the logic so we have early return on error statements, and not, the success case 

Something like:
```swift
if (value.type.name != "Array" || readableArray.size() != 4) {
   Logger.e(RNMBXRasterSourceManager.REACT_CLASS, "source bounds must be an array with left, bottom, top, and right values")
   return
}

val bboxArray = Array(4) { i -> readableArray.getDouble(i)
source.setSourceBounds(bboxArray)
...

2024-10-30 11:03 UTC, Elter71 commented
@mfazekas All suggestions have been applied. Thanks for the quick response!

2024-10-30 11:10 UTC, mfazekas approved these changes

2024-10-30 12:17 UTC, mfazekas commented
@Elter71 thanks much, amazing!

2024-10-30 12:17 UTC, merged