Bugfix/unmount memory leak
rnmapbox/maps pull request #3708
Opened 2024-12-01 15:44 UTC by g4rb4g3

## Description

Fixes an issue that memory would not be freed up when the MapView was unmounted on iOS.

## Checklist

- [x] I've read `CONTRIBUTING.md`
- [ ] I updated the doc/other generated code with running `yarn generate` in the root folder
- [x] I have tested the new bugfix on `/example` app.
  - [x] In V11 mode/ios
  - [x] In New Architecture mode/ios
  - [ ] In V11 mode/android
  - [ ] In New Architecture mode/android
- [ ] I added/updated a sample - if a new feature was implemented (`/example`)

## Screenshot OR Video
without this memory consumption increases whenever a new MapView is mounted
![Bildschirmfoto 2024-11-29 um 13 01 16](https://github.com/user-attachments/assets/2122c4e3-ec74-4330-aae8-bf89199a0800)

with this fix memory is freed up when a MapView is unmounted
![Bildschirmfoto 2024-12-01 um 15 31 35](https://github.com/user-attachments/assets/bd93d0e8-67a4-49fe-8eae-9c227d55ebad)

## Component to reproduce the issue you're fixing
I've updated the ShowMap.tsx and added an (un)mount button there. Whenever you press this button and a MapView is mounted memory usage increases but never decreases when unmounting unless this fix is in place.

2024-12-01 18:48 UTC, g4rb4g3 commented
I just double checked on Android and it seems like this is an iOS issue only.
Whenever the map is unmounted the memory consumption goes down and raises again when the map is mounted again.
![image](https://github.com/user-attachments/assets/d09fa71a-22ee-46a2-877a-fb772ea82699)

2024-12-27 09:41 UTC, mfazekas requested changes
Thanks, looks great to me. 


Note that those examples shows as a documentation, we don't want to pollute them.

Maybe we can add new example for testing just this, what do you think? 

https://rnmapbox.github.io/docs/examples/Map/ShowMap

2025-01-07 09:04 UTC, g4rb4g3 commented
Sure, I just pushed an update moving the example to a new file.

2025-01-09 14:27 UTC, mfazekas commented
@g4rb4g3 you'll need to run yarn generate

2025-01-09 14:39 UTC, g4rb4g3 commented
> @g4rb4g3 you'll need to run yarn generate

Doing so gives me an error about an invalid babel version, but it is exactly the one from package.json

```
➜  maps git:(bugfix/unmount-memory-leak) ✗ yarn generate
yarn run v1.22.19
$ node ./scripts/autogenerate.mjs
(node:41108) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Generating MapboxStyles.d.ts
Generating RNMBXStyle.swift
Generating RNMBXStyleFactory.kt
Generating styleMap.ts
$ yarn tsc --build plugin
$ /Users/manuel_auer/github/maps/node_modules/.bin/tsc --build plugin
$ cd example; jest __tests__/dumpExamplesJson.ts
 FAIL  __tests__/dumpExamplesJson.ts
  ● Test suite failed to run

    [BABEL] /Users/manuel_auer/github/maps/example/node_modules/react-native/jest/react-native-env.js: Requires Babel "^7.22.0 || >8.0.0-alpha <8.0.0-beta", but was loaded with "7.19.1". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel. (While processing: "/Users/manuel_auer/github/maps/node_modules/@babel/plugin-syntax-import-attributes/lib/index.js")
```

So I updated it to 7.22.0 to run generate but did not commit it, maybe you can double check on that?

2025-01-13 20:24 UTC, merged